### ISSUE TITLE
窗口置顶

### ISSUE THREAD

**Issue by Hunlongyu** [shuax/MouseInc.Settings#10]
使用鼠标手势, 让窗口最小化. 然后用 `alt + tab`  切出来, 应用会永久置顶. 微信, Chrome, vscode 等软件, 均出现这个状况. 关键不知道如何关闭置顶.设置里只有一个置顶的说明, 但是没有那个手势是开启关闭置顶.
对日常办公造成困扰, 希望大神看看什么情况.

windows 1909 专业版 64位
MouseInc 2.10.8

**Comment by shuax** [comment]
https://docs.shuax.com/MouseInc/#/faq#%E5%81%B6%E5%B0%94%E5%87%BA%E7%8E%B0%E7%AA%97%E5%8F%A3%E7%BD%AE%E9%A1%B6%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%9F

试试这个，还不行我也没办法了。

**Comment by ttttmr** [comment]
置顶功能应该是可逆的，再同样操作一下就可以取消置顶了
所以可以叫 窗口置顶切换（逃
