### ISSUE TITLE
谷歌浏览器突然用不了这个软件了

### ISSUE THREAD

**Issue by MapleLeaf626** [shuax/MouseInc.Settings#112]
谷歌浏览器突然用不了这个软件了
之前还能用的，今天突然就用不了了，检查排除列表也没谷歌浏览器。重启电脑和安装最新版也没用。不知道是什么导致的

**Comment by shuax** [comment]
可能是管理员权限问题

**Comment by MapleLeaf626** [comment]
> 可能是管理员权限问题

好的，谢谢
我重新启动授予管理员权限就能够使用了
