### ISSUE TITLE
软件非常棒,但是有一个小问题,就是自动复制粘贴的问题

### ISSUE THREAD

**Issue by 1572365765** [shuax/MouseInc.Settings#12]
下面请听我娓娓道来
 我只要选中文字就恢复知道剪切板上,但是当我选中文字粘贴的时候他就不会粘贴原来的内容了,而是粘贴我刚选中文字,我擦,把我自己也说懵逼了.上图
![456](https://user-images.githubusercontent.com/32454224/76924571-b7f70080-6911-11ea-89e7-c00fbefb3e58.gif)
作者可以参考一下cent浏览器的自动复制,我不知道谷歌浏览器有没有这个功能,就是在选中复制的时候会复制上一条结果

**Comment by shuax** [comment]
![image](https://user-images.githubusercontent.com/6940583/76967648-a853d800-6962-11ea-9d73-2703aa250014.png)
目前可以按住ctrl临时禁用，后续优化我再多看看。
