### ISSUE TITLE
如何让Chrome浏览器仅忽略手势但是保证其他功能的使用

### ISSUE THREAD

**Issue by nailao** [shuax/MouseInc.Settings#14]
不想在Chrome浏览器使用手势功能，但是又想在浏览器继续使用快速窗口移动，复制增强，滚轮穿透，又可以在其他窗口正常使用手势功能，现在把Chrome浏览器加入排除软件列表，就所有功能都不能使用了。

对了，截图参考功能很好评，但是不能缩放，这个不太方便，滚动透明功能觉得可以改成缩放，目前还不能让我停止Setuna，自己绘画轨迹确实没有拖拽方框选区来舒服精确。

最后支持作者，很惊艳的一款鼠标增强软件，加油！

**Comment by shuax** [comment]
目前排除不能细化到每个功能，双击就是缩略图。

**Comment by standin000** [comment]
删掉custom match针对浏览器里面手势的部分吧。

**Comment by nailao** [comment]
> 目前排除不能细化到每个功能，双击就是缩略图。

双击缩放图太小了，而且是局部的，想要的是那种缩放百分之多少的。
