### ISSUE TITLE
能否考虑开发文本扩展软件

### ISSUE THREAD

**Issue by lbgws2** [shuax/MouseInc.Settings#164]
mouseinc极大的提高了我的工作效率，之前用过N款鼠标手势软件，要么兼容性不好，要么功能不够强
mouseinc真的非常惊艳，极小的程序体积下，完成了这么多功能
耍下能否考虑开发一下文本扩展软件，比较有代表性的如textexpander，mac平台下有keyboard maestro,我现在使用的是一款叫作fastkeys文本扩展软件，功能比较多，但是基本的文本扩展功能仍然不理想，如文本扩展只能在行尾插入，而移动到文字中间就无法触发了
希望大神能开发出类似的软件出来，谢谢

**Comment by shuax** [comment]
我研究研究
