### ISSUE TITLE
OCR 不能使用，一用就提示“发生未知错误”

### ISSUE THREAD

**Issue by guotangfeng01** [shuax/MouseInc.Settings#175]
### Discussed in https://github.com/shuax/MouseInc.Settings/discussions/174

<div type='discussions-op-text'>

<sup>Originally posted by **190767486** October 13, 2021</sup>
OCR 不能使用，一用就提示“发生未知错误”， 是什么原因？我猜测是次数原因，另外我想请教一下是用的百度OCR还是华为OCR服务或者其他？ 如果我想换成百度OCR，在哪里调API Key这些？
![image](https://user-images.githubusercontent.com/92421340/137072498-d176357e-9ebd-41a6-a968-01778ac21784.png)</div>

**Comment by shuax** [comment]
有道的，改不了
