### ISSUE TITLE
windows11 已经开启忽略全屏了，触发角仍然生效

### ISSUE THREAD

**Issue by lvyao** [shuax/MouseInc.Settings#203]
系统 22000.376
mouseinc 2.11.7

打lol的时候总要关掉触发角，设置里无论全屏还是无边框都会触发。
配置文件

https://pastebin.com/cry0MfRU

**Comment by shuax** [comment]
确实，我看看

**Comment by shuax** [comment]
已经修复

**Comment by lvyao** [comment]
更新后可以了👍
