### ISSUE TITLE
【建议】增加选中文本网页搜索

### ISSUE THREAD

**Issue by rockbenben** [shuax/MouseInc.Settings#21]
对选中的文本进行搜索，建议参考 WGestures
![image](https://user-images.githubusercontent.com/28252913/77314795-4f5cb900-6d41-11ea-8f1a-df1e3a87c5dd.png)

**Comment by shuax** [comment]
S不就是吗

**Comment by rockbenben** [comment]
按回复用右键+S解决了。希望能多集成一些实用功能，降低初学者研究快捷键的门槛
[
	["SendClick", "right"],
	["SendKeys", "s"]
]

**Comment by shuax** [comment]
![image](https://user-images.githubusercontent.com/6940583/77845412-540deb00-71e1-11ea-83c3-365cb44076a6.png)
