### ISSUE TITLE
Win11 Chrome播放多媒体声音，鼠标滑动边缘音量控制，不会出现控制框

### ISSUE THREAD

**Issue by xj179** [shuax/MouseInc.Settings#238]
Win10不会现上述情况 ，chrome播放多媒体声音的时候 ，边缘鉵发调节音量。音量Bar右边会出现一个控制框可以控制上一首，下一首，暂停等 。升级Win11后此功能没有了，只有单纯的调整音量，音量Bar右边 的控制框不见了~

**Comment by shuax** [comment]
这个是mouseinc应该没啥关系
