### ISSUE TITLE
用全局热键把 Chrome 窗口隐藏到托盘之后无法恢复

### ISSUE THREAD

**Issue by Naco** [shuax/MouseInc.Settings#24]
用全局热键 Win+Shift+Z 把 Chrome 的窗口隐藏到系统栏之后，鼠标怎么点都无法恢复窗口，只能去任务管理器杀进程。而且即便杀掉了进程，系统栏任然会有一个 Chrome 的图标。

试过其他例如资源管理器、Edge等应用程序没有这个问题。

**Comment by shuax** [comment]
测试没问题，我一直用的chrome

**Comment by shuax** [comment]
我好像试出来了，和Chrome没关系，影响2个窗口，只能还原一个窗口。
