### ISSUE TITLE
截图参考功能优化建议

### ISSUE THREAD

**Issue by sanan2015** [shuax/MouseInc.Settings#25]
截图参考功能非常使用，无论是对于日常或者工作使用都非常有帮助。需要对比参考的内容，需要暂时存起来的内容，都可以放在屏幕上，稍后处理。

目前遇到的问题是：
1、手势难识别：我为了方便设置了“J“字形的手势，发现长宽比较大或较小就会识别不出来
2、难截图较小区域的内容：要控制好鼠标画的区域
3、难截图较大区域的内容：要控制好鼠标画很大区域也不容易，画出来的不够精确

圈出来的内容因为都是截图成矩形，我觉得可以采用普通截图圈选的方式

非常希望耍大可以优化一下，建议如下：
触发截图参考之后再展示类似截图界面（类似QQ截图），可以通过鼠标圈住区域，同样是正方形的
同样的操作也可以用在OCR上，用户操作起来简便一些（类似天若OCR）

触发操作可以配置：热键、手势触发

感谢耍大带来这么实用的工具，我算是骨灰级用户了，从15or16年就一直用mouseinc和GC，中间切换到WGestures，这两年看耍大更新，重新切换到mouseinc，也是越来越好用了。使用WGestures的手势识别会准确些，识别错误率较低，耍大可以尝试一下WG看看有没有帮助。 @shuax

**Comment by shuax** [comment]
准备借用win10的截图工具，然后从剪贴板进行ocr。

**Comment by shuax** [comment]
新版加入了矩形截图。
