### ISSUE TITLE
一些系统界面下无法使用ORC等问题

### ISSUE THREAD

**Issue by zaxbpc0** [shuax/MouseInc.Settings#251]
问题1：比如打开设备管理器（Windows10系统），此时就无法使用OCR
问题2：打开浏览器打开多个页面后，ctrl+n再打开不同窗口时，就无法使用手势完成“恢复关闭的页面”等操作，重启系统后又恢复
问题3：关于自定义鼠标手势，能否自动识别成直线，半圆，圆等基本图形。鼠标画的太难看了，也存在识别率问题

用了快2年的，已经离不开了，非常感谢大佬提供的高效工具！

**Comment by zaxbpc0** [comment]
仅仅提出些使用问题，以及小建议，不是催更，但期待她越来越完善

**Comment by shuax** [comment]
用管理员模式运行哦

**Comment by zaxbpc0** [comment]
只问题1解决了
