### ISSUE TITLE
更新之后，设置界面打不开了

### ISSUE THREAD

**Issue by xfdj** [shuax/MouseInc.Settings#256]
更新到2.12.0版本之后，打开设置界面变成下面的样子了。
![image](https://user-images.githubusercontent.com/38575841/162559081-672b5f51-2c48-4051-b096-307002efa176.png)

**Comment by shuax** [comment]
系统环境贴一下，是win10吗。

可以尝试手动装一下 https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by czz404** [comment]
同样的问题，系统是win10最新版

**Comment by czz404** [comment]
手动安装后显示正常了

**Comment by shuax** [comment]
新版应该修复了，不用安装webview2也能显示。

**Comment by xfdj** [comment]
2.12.1问题已修复
