### ISSUE TITLE
win11浏览器播放多媒体，鼠标调节音量右边不会有控制bar

### ISSUE THREAD

**Issue by xj179** [shuax/MouseInc.Settings#262]
win10上面正常。如图
![mmexport1649924670001](https://user-images.githubusercontent.com/11533723/163349559-cc6395b3-2e19-4db8-bf0c-d05dcd605548.jpg)
但电脑升级win11之后音量右边那个控制窗没有了，作者大大，这个是什么原因啊。有那个控制窗很方便，上一首下一首就不用打开浏览器操作

**Comment by shuax** [comment]
和mouseinc没关系吧

**Comment by xj179** [comment]
> 和 mouseinc 没关系吧

是嘛，但用这个MouseInc 才会出现音量控制，然后右边才有个控制框。不使用这个鼠标调节音量这个框根本不会出现，所以和mouseInc看起来有点关系~

**Comment by shuax** [comment]
你换个有音量键的键盘就知道了。

**Comment by xj179** [comment]
> 你换个有音量键的键盘就知道了。

作者大大威武啊，一针见血。 一语点破真相。应该就是这个原因了~
