### ISSUE TITLE
alt+tab 实现方式

### ISSUE THREAD

**Issue by S-Kee** [shuax/MouseInc.Settings#266]
在快速切换程序时，经常使用按住alt键后，再多次点按tab键选择要切换的程序。或者按住alt键后，点按tab键，用鼠标点选要切换的程序。不知道用MouseInc如何实现这样的操作。

**Comment by S-Kee** [comment]
> 

边缘滚动是滚动+，滚动-，按住中键三个独立的动作。和我说的不是一回事。我说的是保持alt键按住不放，点按tab键。和单独按alt+tab不一样

**Comment by shuax** [comment]
那就实现不了
