### ISSUE TITLE
webview2

### ISSUE THREAD

**Issue by blackdarks** [shuax/MouseInc.Settings#268]
耍大，我看你这里更新了一个webview2的东东，是不是只要安装了这个，然后把离线包放在mouseinc目录内就可以了？需要解压吗？

**Comment by shuax** [comment]
如果你有webview2，不需要解压，放在目录就能调用。

**Comment by shuax** [comment]
具体你看 https://github.com/shuax/MouseInc.Settings/releases 的图就知道了。
