### ISSUE TITLE
关于键盘按键声音开启后的问题(使用的青轴)

### ISSUE THREAD

**Issue by hea7en2** [shuax/MouseInc.Settings#27]
当长按某个键时键盘声音会一直响，建议修复下，一个按键按一下只会响一次，真实模拟机械键盘的声音 ，谢谢！

**Comment by shuax** [comment]
主要是我的不喜欢最后按键放开是时候没声音，然后声音混响不好做。你可以把声音的开头部分拉长，基本可以实现你说的效果。

**Comment by hea7en2** [comment]
请问下声音开头拉长这个在哪里设置，没有找到，比如要单个多选复制，按住Ctrl就一直响，这样会感觉怪怪的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shuax"<notifications@github.com&gt;; 
发送时间: 2020年3月28日(星期六) 下午3:16
收件人: "shuax/MouseInc.Settings"<MouseInc.Settings@noreply.github.com&gt;; 
抄送: "胡汉文"<88261565@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shuax/MouseInc.Settings] 关于键盘按键声音开启后的问题(使用的青轴) (#27)





 
主要是我的不喜欢最后按键放开是时候没声音，然后声音混响不好做。你可以把声音的开头部分拉长，基本可以实现你说的效果。

**Comment by shuax** [comment]
编辑音频：Audacity
提取替换资源：Resource Hacker
编码转换：ffmpeg
