### ISSUE TITLE
4k屏下手势延迟问题的一个可能的解决思路

### ISSUE THREAD

**Issue by lijian12345** [shuax/MouseInc.Settings#299]
我自己的笔记本显卡是3060，屏幕是4k屏，发现每次画手势的时候GPU占用率飙升到30%左右。
因此感觉可以加一个开关关闭画出来的手势线的抗锯齿效果，或者降低画出来的线的分辨率，可能会解决延迟问题。

**Comment by shuax** [comment]
什么都不画也会卡，窗口太大了。唯一不卡就是关掉显示。

**Comment by lijian12345** [comment]
> 什么都不画也会卡，窗口太大了。唯一不卡就是关掉显示。

😂
