### ISSUE TITLE
强烈建议可以增加其他按键的手势

### ISSUE THREAD

**Issue by qstdnx** [shuax/MouseInc.Settings#30]
wgesture转过来的，因为右键拖动在windows有他功能比较常用，所以一直用的是中键来触发所有手势的，虽然常见问题里写了不打算开发这个功能，还是秋梨膏膏。
http://tu.yaohuo.me/imgs/2020/04/5af5f95254f44fea.png

**Comment by shuax** [comment]
暂不考虑
