### ISSUE TITLE
请问大佬如何备份自己的配置文件

### ISSUE THREAD

**Issue by hausen1012** [shuax/MouseInc.Settings#302]
由于配置实在花了太久时间，下次重装系统或者换电脑可以直接使用之前的配置会比较好

**Comment by shuax** [comment]
https://docs.shuax.com/MouseInc/#/faq#%E5%A6%82%E4%BD%95%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA%E8%AE%BE%E7%BD%AE%EF%BC%9F

**Comment by hausen1012** [comment]
感谢
