### ISSUE TITLE
新功能建议：添加鼠标滚轮速度调节功能

### ISSUE THREAD

**Issue by charygao** [shuax/MouseInc.Settings#32]
运行“rundll32 shell32,Control_RunDLL main.cpl,,3”，可以看到【滑轮】/[垂直滚动] 标签页 滚动滑轮一个迟格到：“一次滚动下列行数”和“一次滚动一个屏幕” 
![image](https://user-images.githubusercontent.com/6499936/80563459-d4607f80-8a1d-11ea-8149-28841ea00d05.png)
希望添加 
1.切换 一次滚动下列行数 / 一次滚动一个屏幕 的功能；
2.快速调节 滚动行数 的功能；
谢谢大佬。

**Comment by charygao** [comment]
自觉关闭。

**Comment by shuax** [comment]
过于私人的功能，不考虑。如果要实现类似效果，可能会加入设置注册表的功能。
