### ISSUE TITLE
使用了一阵子，说点心得

### ISSUE THREAD

**Issue by kevzcr** [shuax/MouseInc.Settings#324]
Mouselnc，怎么说呢，我不喜欢开机运行东西，但它例外。
总结一下，软件以四种方式实现快捷应用：手势，快捷菜单，全局热键。另加一种就是勾选软件自带选项。  
注：初用者一次加一二个功能，用熟练了再加入新。 我第一次用这个软件时，打开后研究了半天，放弃了，和以前用过的软件有很大的不同，需要很强的动手能力，是优点也是缺点吧，太挑人了。
还是谈谈我是如何使用的。
第一种，手势  
我将平时最常用到的复粘剪删，QTranslate翻译，Evething搜索 设置成X型即↖↗，↙↘及 ↑↓，6个方向。再加上个Mouselnc设置 M 型。共7种手势。  
第二种，快捷菜单  
百度，谷歌，Deepl
使用方法：复制好文字，Ctrl+c&c  在弹出的小菜单里选，点百度等，就会自动打开浏览器对所选文字直接进行搜索，翻译。
（软件设置中的有道翻译等无法完成直接调用，需要在打开的界面粘贴再操作，一直没搞明白乍弄，请赐教）
第三种，全局热键
ocR，截图，程序调用   我把最好用的快捷给了它  shift+win+Z
重点来了，，，，，，，，，，，，，，，，，，，，，，，，，，，
1.框选OCR，这个一定要勾选上，太好用了，此处省略成千上万字，无法用语言来表述。
2.框选画中画。 即截取一个克隆的小窗口。
3.暂停恢复Mouselnc   有时和别的软件热键冲突等，你需要暂停一下
4.截图－全屏
5.截图－框选
6.贴图     456三项就是系统截图和snipaste的最佳替代.
(强烈希望作者加入简单编辑功能，比照snipaste，如果再加上截长图，~啪。。醒醒，，)
第四种，软件设置里的自带选项
音量调节，切换标签 
       以上我说的每一种功能的尝试，都让我感慨，作者就是个鬼才，软件仅仅只有小小的800KB，却如此强大，回想最开始接触时，我对编程一点也不懂，学起来很累很累，但软件能实现的功能强烈吸引着我，最终一点一点地学会了怎么设置，太难了，没为哪个软件下过这么大的功夫，但，值！ 感谢作者的辛勤劳动。 
后期期待
       希望作者能让软件更易用一些，门槛有点高，能否把最常用的几种默认勾选，在醒目位置图示说明一下使用方法，几种就够了，好东西就应该让更多的人都用用。学习如何使用Ml这条路一路走下来真不容易呀。在聪明的人眼里，什么都应该学起来不难，可是还是笨人多呀对不。
       截图这块希望作者能加上几种编辑功能，那样的话，电脑上的截图软件真就没存在的意义了。现在偶尔还会用到snipaste，其实就用它添个箭头画个框写两个字。现在已经有了Ml 常驻后台，就不想再打开其它软件了。  
码了这么多字，值！

**Comment by Sanhuaitang** [comment]
这个需求我觉得你用专门的截图工具比较好  snipaste之类
mouseinc把手势发挥到极致才是正经的
