### ISSUE TITLE
发现OcR功能出现问题不能用了

### ISSUE THREAD

**Issue by kevzcr** [shuax/MouseInc.Settings#327]
出问题时正在设置CapsCursor这个软件，也是一个可设置很多快捷操作的软件，主要和Capslook键有关，所以发现OCR出了问题后，我先把Cap..软件改变的设置都还原了，发现没解决问题，重启了电脑，还是不行，索性就把Caps..删除了，也不行，想了想，也许是服务器之类的问题吧，等第二天再看， 今天试了多次，发现还是不行。

**Comment by Nicholasjl** [comment]
我也有同样的问题

**Comment by kevzcr** [comment]
今天专门把系统重新做了，可以确认就是软件本身的问题。

**Comment by kevzcr** [comment]
OCR解决了，设置进不去也解决了，本来还想让作者加入个截图修改功能，算了，就这样了，99分了，只想要个稳定运行版 。
有种感觉，Mouselnc这种软件形式正成为潮流，有点门槛，但动动手更快乐。
软件非常棒。 再次感谢！

**Comment by Tracker647** [comment]
> OCR解决了，设置进不去也解决了，本来还想让作者加入个截图修改功能，算了，就这样了，99分了，只想要个稳定运行版 。 有种感觉，Mouselnc这种软件形式正成为潮流，有点门槛，但动动手更快乐。 软件非常棒。 再次感谢！

问下最后是怎么解决的呢
