### ISSUE TITLE
提示更新2.13,但是无法成功更新

### ISSUE THREAD

**Issue by LowkeyLee** [shuax/MouseInc.Settings#336]
只是在temp目录生成了一个mouseinc2.12.1的exe,就没有下文了!!!大家有这个情况吗?以为会更新OCR识别,看来不是

**Comment by shuax** [comment]
https://dl.shuax.com/MouseInc2.13.0.7z
手动更新试试

**Comment by cc19264997** [comment]
> https://dl.shuax.com/MouseInc2.13.0.7z 手动更新试试

2.13都更新了什么呀？OCR还是无法正常使用呢

**Comment by LowkeyLee** [comment]
> https://dl.shuax.com/MouseInc2.13.0.7z 手动更新试试

谢谢大佬回复我,OCR接口是不是限额了,还是更换了呢,如果可以自定义OCR 的api就好了!

**Comment by cc19264997** [comment]
> 只是在temp目录生成了一个mouseinc2.12.1的exe,就没有下文了!!!大家有这个情况吗?以为会更新OCR识别,看来不是

我这没有你说的temp目录的情况，感觉就是刷了个版本号。。

**Comment by EK-night** [comment]
> https://dl.shuax.com/MouseInc2.13.0.7z 手动尝试更新
更新到最新2.13了之后OCR还是无法用发生未知错误呢，但是界面就进得去不会一直加载转圈了。
