### ISSUE TITLE
配置界面无法加载

### ISSUE THREAD

**Issue by xsb0624** [shuax/MouseInc.Settings#347]
配置界面一直显示loading，版本为最新

**Comment by Tracker647** [comment]
同，另ocr无法使用

**Comment by jtgtifh** [comment]
我也是。在线配置前两天开始突然打不开。布署到本地，打开设置也是显示为loading.

**Comment by sy158465** [comment]
https://github.com/shuax/MouseInc.Settings/discussions/337#discussioncomment-3497058

**Comment by Eunknight** [comment]
> 同，另ocr无法使用，显示未知错误



> 同，另ocr无法使用，显示未知错误

https://github.com/shuax/MouseInc.Settings/discussions/335#discussioncomment-3523123

**Comment by Eunknight** [comment]
> 同，另ocr无法使用，显示未知错误

https://github.com/shuax/MouseInc.Settings/discussions/335#discussioncomment-3523123
