### ISSUE TITLE
按键回显功能能否参照keycastow  多一些设置呢

### ISSUE THREAD

**Issue by Sanhuaitang** [shuax/MouseInc.Settings#372]
例如： 最大行数（目前是无限行）、 从下往上显示（目前只有从上往下：最新的按键在上面）  鼠标动作（显示左右按键、滚轮操作，是否忽略）

如果能实现这些 就完美了
感谢您的软件！日常效率得到极大提升！

**Comment by shuax** [comment]
毕竟这个不是主打功能，难得做了。

**Comment by Sanhuaitang** [comment]
> 毕竟这个不是主打功能，难得做了。
好吧
鼠标动作麻烦的话 可以不弄
但是 最大行数（比如5行）、 从下往上显示     要是能有也很好了
