### ISSUE TITLE
Windows security blocks the update

### ISSUE THREAD

**Issue by HsuJv** [shuax/MouseInc.Settings#38]
Hi there,

Thanks for providing so powerful a tool which gives my life so many conveniences.

But there also some trouble things which I've ever met.

The issue I met was:
1. At the very first, I was trying to close the auto-update, but then I've found that it is un-supported in the Q&A.
2. Then I was trying to permit the upgrade. But the Windows security (actually it was Windows Defender) blocks the update as this program trying to upgrade with a download file which stores @ %LOCALAPPDATA%\Temp\Mou****.tmp, but Trojan:Win32/Occamy.C was detected.
3. Temporarily allow this threat will not be helpful since the name of this temp file is different every time.
4. I will never agree on adding the dir %LOCALAPPDATA%\Temp to the exclude of Windows Securty as it will be so dangerous.
5. Actually, I configure a set of dirs which used to run the "developer tools"  (which I mean is the programs may be found trojans by win defender), and so do this MouseInc. All these folders' permissions are configured carefully so that it won't affect other trusted programs.

So kindly advise is there any solution the bypass the updating without adding %LOCALAPPDATA%\Temp to the excluded list.

Or is it possible to change the storage of this temp file to the current dir which runs MouseInc and delete it after upgrading?

Thanks in advance.
BRs.

**Comment by shuax** [comment]
报毒手动处理吧，就不要自动更新了。

**Comment by HsuJv** [comment]
Sure, I'll do it manually.

But will there be any way to block the update pop-up?
