### ISSUE TITLE
反馈问题：2.10.18版本上Snapshot会出现调不出来的情况

### ISSUE THREAD

**Issue by sanan2015** [shuax/MouseInc.Settings#39]
hi，耍下：

2.10.18版本，近期更新后发现Snapshot出现调不出来的现象（之前正常使用），使用全局快捷键、手势调用以下两个操作都出现闪一下，没有正常运行截图：
[[ "Snapshot", "Stick"]]
[[ "Snapshot", "OCR"]]

刷新配置，无效
退出重启，中间有几秒钟确实调出来了，上面两个功能都可以，但很快再试就无法调出

**Comment by shuax** [comment]
这个截图在失去焦点后会自动退出，所以有可能是什么程序在抢焦点。

**Comment by shuax** [comment]
win7测试按不出来，这周末应该会修复一下。

**Comment by sanan2015** [comment]
> win7测试按不出来，这周末应该会修复一下。

最近没上github看消息，刚更新最新版发现ok了，很棒~
