### ISSUE TITLE
自动隐藏桌面文件，图标

### ISSUE THREAD

**Issue by a1waysbeta** [shuax/MouseInc.Settings#391]
是否可以增加临时隐藏桌面图标，文件功能？方便截图时背景干净。
类似于：https://www.52pojie.cn/thread-1684581-1-1.html
减少一个软件安装

**Comment by shuax** [comment]
这个还挺不错的，我试试

**Comment by shuax** [comment]
`["Explorer", "ToggleDesktopIcons"]`

**Comment by a1waysbeta** [comment]
太棒了，感谢
