### ISSUE TITLE
如果能增加悬停激活标签页功能就可以彻底抛弃FireDoge了

### ISSUE THREAD

**Issue by operammm** [shuax/MouseInc.Settings#4]
还在用FireDoge1.0，因为加载速度最快，开启火狐时鼠标光标不会像1.0以上的版本一样有一个转圈的效果，缺点是不能用网页设置功能。

最近火狐更新了，FireDoge的前进后退不好使了。我就试试MouseInc，感觉还行，就是缺少悬停功能。

我改了下FireDoge.ini中的快捷键，前进后退又复活了。_(:з」∠)_
4E7908C1=后退|SendKeys|Backspace
C3C6D1DD=前进|SendKeys|Shift+Backspace

**Comment by shuax** [comment]
不打算加。
