### ISSUE TITLE
请问是否有机会实现Chrome浏览器的鼠标滚轮切换标签呢？

### ISSUE THREAD

**Issue by Aponio** [shuax/MouseInc.Settings#40]
软件很棒，应该是现在比较强的一个了，现在用鼠标手势（边缘滚动）全屏时没有问题，鼠标顶到最上面就可以了，但是如果浏览器窗口不全屏，就没办法了。弱弱的问问作者是否考虑增加对Chrome浏览器的鼠标滚轮切换标签呢？谢谢，作者辛苦了~

**Comment by shuax** [comment]
https://shuax.com/project/chrome/
