### ISSUE TITLE
新增输入法状态显示?

### ISSUE THREAD

**Issue by kevzcr** [shuax/MouseInc.Settings#400]
3a84a72 查找了半天也没找到代码，这个功能如何用？
另外`桌面图标显示切换`，很酷。

**Comment by shuax** [comment]
设置第一页就有

**Comment by kevzcr** [comment]
> 找到问题了，我的更新方法不对，不能下载后对旧文件进行替换，会造成软件的版本更新了，但界面却还是老的界面。

> 问题：我下载好的新版如何把老版的设置导入呢？

![image](https://user-images.githubusercontent.com/88956040/189777333-d769c7c1-7ab8-4ed9-83b1-bb69ee7601f0.png)

**Comment by shuax** [comment]
你是不是有老的设置界面离线包，删了。

**Comment by kevzcr** [comment]
`MouseInc.json`  我对照着老版本，逐条修改了这个文件，现在好了。但过程有点麻烦。

![image](https://user-images.githubusercontent.com/88956040/189781559-3b591261-efa8-4e00-b718-3b9f848f2adb.png)

> 问题：直接起用下载的新版，老的设置如何导入？

**Comment by shuax** [comment]
和设置json没关系
