### ISSUE TITLE
使用‘’下右‘’手势可以是关闭当前窗口而不是关闭软件吗？

### ISSUE THREAD

**Issue by guwunianzhi** [shuax/MouseInc.Settings#42]
使用idea开发工具的时候，‘’下右‘’手势可以是关闭当前窗口而不是关闭软件吗？

**Comment by shuax** [comment]
自定义动作

**Comment by guwunianzhi** [comment]
已修改为我想要的，
第一步：将idea 中Settings设置-》Keymap-》Window-》Editor Tabs-》Close添加Ctrl+W为关闭tab快捷键
第二步：MouseInc软件设置中选择 鼠标手势-》特定动作-》程序列表添加idea.exe，然后保存
这样通过使用鼠标‘下右’手势操作即可像浏览器一样关闭当前tab页
