### ISSUE TITLE
鼠标手势中的顶底部滚动在edge浏览器里失效了

### ISSUE THREAD

**Issue by AdwardA** [shuax/MouseInc.Settings#446]
之前还能用的，在Chrome浏览器里也可以，不知道为什么现在用不了了。
鼠标手势也是生效了的，就是只在一行文字的首末端切换，而不是页面的滚动
你们有这样的情况吗

**Comment by AntoBeyondSuy** [comment]
我是 win10 21H2，MS edge 105.0.1343.53 (正式版本) (64 位) 使用正常。更新一下系统和 MS edge 试试？
屏幕上边缘滚轮实际输出的是 Ctrl+PgUp 和 Ctrl+PgDn，要不再确认一下你的配置对不对？（应该是对的
![image](https://user-images.githubusercontent.com/32611245/192810434-64e727c1-b967-4e37-a284-91035f8c6169.png)

**Comment by AdwardA** [comment]
找到问题了，像这个老哥说的，误开启了一个功能
![image](https://user-images.githubusercontent.com/20749371/195334455-55606376-0070-44e8-8ef1-9c39bd407beb.png)


https://www.zhihu.com/question/530681367
