### ISSUE TITLE
shuax大佬再见

### ISSUE THREAD

**Issue by GitHubXieYihang** [shuax/MouseInc.Settings#459]
看来告别信，感慨万千，再见了shuax大佬，希望未来再见

**Comment by SoyKoa** [comment]
在哪里看告别信啊?有链接吗?

**Comment by LARASPY** [comment]
https://github.com/shuax/MouseInc.Settings/issues/459

**Comment by FuzzyMakeup42** [comment]
留下了一个传说

**Comment by hmpgithub** [comment]
真拜拜了呀,大佬

**Comment by hmpgithub** [comment]
> 
.

**Comment by HSJSMARK** [comment]
公安真踏马傻逼，源头不抓抓普通人，我明白冤假错案是怎么产生的了！shuax大佬，我相信你是冤枉的！希望未来再见

**Comment by Zh40Le1ZOOB** [comment]
> 公安真踏马傻逼，源头不抓抓普通人，我明白冤假错案是怎么产生的了！shuax大佬，我相信你是冤枉的！希望未来再见

无能的政府是这样的，抓不到真正的坏人，就抓好欺负的小开发者冲业绩。这种政府不亡谁亡？

**Comment by moyuduo** [comment]
github能言论自由吗

**Comment by Zh40Le1ZOOB** [comment]
> github能言论自由吗

能的，你在这里怎么骂都不会被抓到

**Comment by xp12047** [comment]
惋惜

**Comment by billionfish** [comment]
有人知道nodejs的版本吗
想本地搭建一个

**Comment by lzj242** [comment]
> 在哪里看告别信啊？有链接吗？

https://www.zhihu.com/question/557457155/answer/2699425100

**Comment by lyolve** [comment]
有没有大佬接盘啊，这么好的软件就这样无了多可惜
