### ISSUE TITLE
新的官网地址是多少？

### ISSUE THREAD

**Issue by Kreych** [shuax/MouseInc.Settings#468]
请问新的官网地址是多少，还是取消官网了？作者大大

**Comment by chenchang-create** [comment]
作者因为OCR某库进去了，所以官网无了

**Comment by ChaXxl** [comment]
> 

因为OCR能进去？

**Comment by chenchang-create** [comment]
> > 
> 
> 因为OCR能进去？

详情可以看https://www.zhihu.com/question/557457155/answer/2699425100

**Comment by lyolve** [comment]
我说怎么官网都没了呢，淦，这软件很好用的，有没有大佬接盘项目啊
