### ISSUE TITLE
alt+滚轮和调节亮度

### ISSUE THREAD

**Issue by YYJavaGit** [shuax/MouseInc.Settings#48]
alt+滚轮和调节亮度经常失效， Dbgview没有提示相关错误 win10_1909

**Comment by YYJavaGit** [comment]
我发现了更好用的边缘滚动，边缘滚动可用的状态下，alt+滚轮调节音量还是失效

**Comment by shuax** [comment]
有点奇怪，和特定软件有关吗。你可以打开按键回显来看是否发送了动作。

**Comment by YYJavaGit** [comment]
偶发性bug，没有响应相应的动作，我开了回显没有用，也没有bug日志，非全屏状态，有时候刚开机也会失灵，装的360但是权限杀毒什么的都给了白名单




在2020年06月26日 20:55，shuax 写道：

有点奇怪，和特定软件有关吗。你可以打开按键回显来看是否发送了动作。
