### ISSUE TITLE
设置通道连接失败，可能是MouseInc主程序未更新

### ISSUE THREAD

**Issue by ijrou** [shuax/MouseInc.Settings#484]
主程序：2.13.4
放入了 MouseInc.Settings.zip
打开设置后先Loading...，然后就提示：“设置通道连接失败，可能是MouseInc主程序未更新”；

![](https://img.erpweb.eu.org/imgs/2023/01/442a6fb6c36555d0.png)

**Comment by chinkuang** [comment]
是不是你的mouseinc版本太低了，我用的2.13.4没问题呢

**Comment by ijrou** [comment]
> 是不是你的mouseinc版本太低了，我用的2.13.4没问题呢

我mouseinc版本即使：2.13.4
windows 11 22H2 最新

**Comment by Mo-ke-s** [comment]
mouselnc是用什么技术开发的？这么复杂的应用怎么软件包这么小？

**Comment by wray-lee** [comment]
> mouselnc是用什么技术开发的？这么复杂的应用怎么软件包这么小？

这个软件就是个浏览器，具体功能实现是在作者的服务器上
