### ISSUE TITLE
其他设置-快捷菜单问题

### ISSUE THREAD

**Issue by yapeng99f** [shuax/MouseInc.Settings#49]
添加新的菜单之后,移动是个问题,可通过拖拽调整菜单位置。但实际拖拽效果并不理想,甚至可能是我不会操作,我拖拽之后并没有到达我预期的位置,建议选中按上下键移动,或者作者有更好的解决方式

**Comment by shuax** [comment]
拖动很好用啊，达不到想要的位置可能是多级菜单问题
