### ISSUE TITLE
功能失效了。坏了吗

### ISSUE THREAD

**Issue by adoin** [shuax/MouseInc.Settings#494]
![image](https://github.com/shuax/MouseInc.Settings/assets/20517172/d6e59d6c-7490-4009-b53b-1e120c3e56ea)

**Comment by qianfanguojin** [comment]
作者服务器关了大概，解决办法是下载Release里面的压缩包放到软件运行目录（mouseinc 程序的目录）即可

**Comment by shuax** [comment]
用的ion vps，机房好像着火了，挂了。

**Comment by adoin** [comment]
> 用的ion vps，机房好像着火了，挂了。

啊。。。有没有不需要联网的版本 感觉没联网必要啊

**Comment by osdu** [comment]
> 用的ion vps，机房好像着火了，挂了。

还能上线吗  木得文档难受

**Comment by shuax** [comment]
https://www.vpstop.cn/news/2023-05-23/409.html

文档没啥用吧，自己下一个离线设置就够了。

**Comment by shuax** [comment]
https://github.com/shuax/MouseInc.Settings/blob/master/docs/docs/README.md

这里有文档
