### ISSUE TITLE
win10  任务栏 有时候 右键没反应

### ISSUE THREAD

**Issue by gitlsl** [shuax/MouseInc.Settings#5]
有时候为了切换到桌面  我都是  在任务栏上右键--> 显示桌面     
这个时候就右键任务栏经常没反应
但如果通过其他方法已经切到桌面  再在任务栏右键 就可以正常弹出菜单

**Comment by shuax** [comment]
常见问题有说明，这种多半当前窗口是一个管理员权限的程序，比如任务管理器，此时就无法点右键了。
