### ISSUE TITLE
"DesktopWindow" 无法最小化？

### ISSUE THREAD

**Issue by Dorl121** [shuax/MouseInc.Settings#50]
* 本来是打算使用 **MouseInc** 去替换 **Strokeit** 的。但是，发现有一个功能无法实现，就是对**桌面窗口（DesktopWindow）** 最小化。
* 不知道您使用什么方法实现的 “最小化” ，还是有意屏蔽了**DesktopWindow**？
* 其最小化的效果如下：

![snipaste20200704_171350](https://user-images.githubusercontent.com/32960880/86509428-6ddf4f80-be1a-11ea-9de1-c8749cd61747.jpg)

* 这样可以快速清空桌面，对于很多情况下可以避免尴尬，保护隐私，个人觉得是很好的功能。

**Comment by shuax** [comment]
就是这样设计的，桌面不能被最小化或者移动之类。

**Comment by Dorl121** [comment]
好的，看来只能从 您提供的 内置参数 %pid% 下手，从外部挂程序解决了-_-

感谢您的回复
