### ISSUE TITLE
快捷菜单导致系统无响应（个例）

### ISSUE THREAD

**Issue by cqwzhc** [shuax/MouseInc.Settings#55]
mouseinc神器不解释！
遇到个问题，双击ctrl+c弹出快捷菜单后系统假死，鼠标能动但不能选择快捷菜单，其它软件正常工作，多次点击后电脑滴滴响且鼠标卡顿，等个十来秒钟后恢复响应，快捷菜单可正常使用，procmon监视所有动作均无异常，dbgview无异常输出，其它电脑上正常无此情况，不想重装系统，求其它解决办法。。自己Autohotkey写的弹出快捷菜单的小软件能正常使用

**Comment by shuax** [comment]
部分win7会出现这个情况，暂时无解
