### ISSUE TITLE
关于弹出警告之后莫名其妙非常卡的问题

### ISSUE THREAD

**Issue by kunpeng9** [shuax/MouseInc.Settings#60]
![image](https://user-images.githubusercontent.com/44609485/91830894-f3924680-ec75-11ea-93c6-c6eb6bcc273a.png)
---
如图，不知道为啥我用了管理员启动之后设置那个开机启动还是不行，会特别的卡，卡到我不能点击那个允许软件运行一切操作，也点击不了那个不提醒，实在是太卡了。其他的软件没有出现这个现象，试了一些次都不行，都是这样，卡的要死，不能设置开机自启。
关于剪贴板的问题。
我用wegesture的时候，那个剪贴板没问题的，不知道为啥用这个软件感觉剪贴板似乎没有以前好用了。手势复制时不时没有复制到内容。

**Comment by shuax** [comment]
用不了就不用嘛

**Comment by kunpeng9** [comment]
@shuax  能修复吗？或者确定是啥问题吗？这么快就关闭了嘛，这个issues。
