### ISSUE TITLE
[问题 触发角会和Win10多任务分屏冲突

### ISSUE THREAD

**Issue by Lisuaki** [shuax/MouseInc.Settings#9]
手册上写的在这里反馈来着，不过一个issue都木有？

最近才被人安利了这个来着，原来一直用Wgestures，那个太久没更新啦

软件很好用就是最近添加的触发角功能会和Win10多任务分屏冲突，拖动窗口到四角想分屏的时候就没法分屏了，希望触发角在判定的时候能检测一下鼠标左键是否按下，如果按下的话就不触发触发角的共能呢？

感谢_(:з)∠)_

**Comment by shuax** [comment]
建议不错，下次加上

**Comment by Lisuaki** [comment]
哦吼好快！期待期待( •̀ ω •́ )y

**Comment by shuax** [comment]
已经发布新版
